require_relative "game_of_life_test"
require_relative "readstring_test"
require_relative "readfile_test"
require_relative "bad_size_test"
require_relative "accessors_test"
require_relative "view_test"
